### ISSUE TITLE
세미나 출석 페이지 이름 정렬 순서

### ISSUE THREAD

**Issue by dkstlzu** [PoolC/Mincho#123]
## 🗣 설명
출석 페이지에 들어갈때마다 이름 정렬 순서가 바뀌네요

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1.  가나다순이 좋지 않을까 생각합니다.

**Comment by hcpak** [comment]
가나다 순으로 정렬했습니다. issue 감사합니다.
