### ISSUE TITLE
회원관리 회원상태 추가 건의

### ISSUE THREAD

**Issue by dkstlzu** [PoolC/Mincho#125]
## 🗣 설명
졸업회원이면서 비활동인 회원의 경우 관리할 수 있는 상태가 적절치 않습니다.
해당경우 승인전으로 상태를 바꿔 비활동카테고리로 넘어가게 되는데 그렇게 되면 로그인이 불가능한 상태로 넘어가기 때문에 추가적인 상태관리가 필요할 것으로 보입니다. 현재 상태에서 졸업회원, 수료회원등으로 관리할 경우 활동회원 카테고리에 속하기 때문에 최소활동기준등에도 노출되는등 관리의 불편함이 증가합니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 졸업 + 비활동 회원을 로그인 가능+비활동 카테고리로 관리가능한 회원상태 추가

**Comment by Jjungs7** [comment]
권한은 아래와 같습니다. 승인 전은 정말로 관리자가 회원으로 승인하기 전 상태로 분류했습니다. 따라서 MEMBER 이하 상태만 회원으로 인정하고 있습니다. 최소활동기준에 노출되는 이슈는 곧 구현할 (형철님...^^) 사항으로 비활동~임원진은 자동으로 최소활동기준 면제대상으로 구현할 예정입니다. 혼동을 줄이기 위해 개발진과 임원진끼리 회의하는것도 좋을것같아요

![8CDE6F77-D0C7-4D65-96E8-0DC22866D31D](https://user-images.githubusercontent.com/14287915/112014859-a1136b80-8b6e-11eb-9e63-5756b92718b4.png)

**Comment by dkstlzu** [comment]
비활동, 졸업, 수료, 임원진의 경우 최소활동기준 관리탭에서 빠지도록 변경이 된다면 현재 구조로 적절히 이용할 수 있을것으로 보이네요! 문제없는것으로 보입니다
