### ISSUE TITLE
비활동~임원진 자동 면제

### ISSUE THREAD

**Issue by Jjungs7** [PoolC/Mincho#126]
## 🗣 설명
아래 이슈 참고
https://github.com/PoolC/Mincho/issues/125#issuecomment-804154949

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 최소활동기준 대상/면제 대상 분리 및 사유 표시

**Comment by hcpak** [comment]
아직까지 memberRole에 대해 어떤 원리로 동작하는 지 파악하지 못했습니다. 다시 한번 어떤 동작인지 파악해 4월 12일까지 완료하도록 하겠습니다.

**Comment by hcpak** [comment]
> 735712f 과 같은 방식으로 작성했는데 이렇게 하는 게 맞나요?

**Comment by hcpak** [comment]
> 40e3343 으로 수정했습니다.
