### ISSUE TITLE
세미나 진행시간 다변화

### ISSUE THREAD

**Issue by dkstlzu** [PoolC/Mincho#127]
## 🗣 설명
세미나를 여러 주차에 걸쳐 실시하는경우 각각의 주차가 진행시간이 3시간, 2시간등으로 상이한 경우가 있는데 해당 경우에 적절한 시간설정이 불가능한것으로 보입니다. 이 경우 총무와의 추가적인 소통이 필요할 것으로 보여 본래 취지를 만족시키지 못하는 경우가 발생합니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 세미나 주차별 진행시간 설정 가능 혹은 매 출석시 진행시간을 체크하도록 하는 기능 구현

**Comment by hcpak** [comment]
주차 별로 시간 설정을 다르게 할 수 있도록 변경하도록 하겠습니다. 4월 9일까지 완료하도록 하겠습니다.

**Comment by hcpak** [comment]
저는 기능 구현 완료했는데 @mingd1023 님이 많이 바쁘신가봐요 ^^
