### ISSUE TITLE
시그니처 순서(Member)

### ISSUE THREAD

**Issue by Jjungs7** [PoolC/Mincho#130]
## 🗣 설명

틀린거 있어유

https://github.com/PoolC/Mincho/commit/625873cfbad7d81dd52840a2a9dda8bca350985e#diff-aedb8e31440e028d3db988f0d64bd80a71c11154d36345bd469f0dbd039dca4aR28

**Comment by hcpak** [comment]
앗 login id 순서가 잘못되었군요... 수정하도록 하겠습니다.

**Comment by hcpak** [comment]
수정했습니다!
