### ISSUE TITLE
envrc 띄워쓰기

### ISSUE THREAD

**Issue by Jjungs7** [PoolC/Mincho#131]
## 🗣 설명
shell 스크립트에서 변수명 선언할때 variable=value 사이에 띄워쓰기가 있으면 에러나요
혼동을 줄이기 위해 이 커밋은 돌리는게 좋을 것 같아요 (git revert 기능을 써봅시다)
c1315fa2ec14d31bc08fc431ce45b8e627e3e3e2

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. git revert로 되돌리기

**Comment by Jjungs7** [comment]
![Uploading Screen Shot 2021-03-31 at 8.39.55 PM.png…]()

**Comment by hcpak** [comment]
이거 제가 따로 수정한 게 아니라 intellij에서 plugin 설치 후 자동으로 띄어쓰기가 동작했던 거 같습니다. 수정하겠습니다.

**Comment by hcpak** [comment]
git revert를 이용해 수정했습니다!
