### ISSUE TITLE
메일 보내는 기능 wrapper class

### ISSUE THREAD

**Issue by Jjungs7** [PoolC/Mincho#132]
## 🗣 설명
메일 기능 👏👏👏
https://github.com/PoolC/Mincho/commit/ef454b0a5745bd095190f9c636a76c0a13b9b915#diff-3eaf02b66dc9e1f979e570f0620965c4d693d1c26561ea75ccff643633efc47aR186

JwtTokenProvider 처럼 wrapper class를 구현하는게 어떨까요? getter 없이 딱 필요한 기능들만 제공하는 방식으로요

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. mail api 분리 및 wrapper class 구현
2.

**Comment by hcpak** [comment]
아하 그거 좋은 생각인 거 같습니다. Wrapper 클래스를 작동하도록 만들겠습니다. 아 그리고 nagase에서 sendgrid api key를 사용하는 것을 보았는데, api를 사용하는 이유에 대해서 알고 싶습니다. 보안적으로 훌륭하다거나, 아니면 사용하기 간편해서 쓰는 건지 궁금합니다.

**Comment by Jjungs7** [comment]
어... 제가 구현한건 아니라서 정확히는 모르겠네요 ㅋㅋㅋㅋㅋ sendgrid는 aws 서비스입니다. 서버가 aws 클라우드에서 돌아가고 있기 때문에 메일 보내는 서비스도 같은 클라우드에서 사용했을 뿐이에요

**Comment by hcpak** [comment]
구현했습니다!
