### ISSUE TITLE
WrongPasswordException 관련

### ISSUE THREAD

**Issue by Jjungs7** [PoolC/Mincho#133]
## 🗣 설명
https://github.com/PoolC/Mincho/commit/9eacda1acd237ce815bcfad76bc99542e52fba4a#diff-bb1a3c4021880d05850ad8a66566da92b7db87b5a4de248df6346a8fe2d4fc3fR18

Exception 분리하는거 좋아요! 근데 이런건 메시지나 코드로 전달하는게 어떨까요
예를 들어, 회원가입할 때 email이 틀렸으면 WrongEmailException 만들고, 학번이 형식에 안 맞으면 WrongStudentIDException 만들고, loginID가 형식에 안 맞으면 WrongLoginIDFormatException 만들고.... ~~그만~~

이런건 error code 같은거나 메시지로 구분하게 하면 좋을 것 같아요
큰 틀에서 보면 로그인정보가 틀렸으니 어쨋든 인증되지 않은 회원이니까 Unauthenticated이 맞을거고 메시지나 에러코드를 보내면 되겠죠?
[Nagase](https://github.com/PoolC/Nagase/blob/master/docs/Spec.md#%EC%97%90%EB%9F%AC-%EC%BD%94%EB%93%9C)에서 했던 방식을 참고하면 좋을 것 같네요 ([SigAhri쪽 코드](https://github.com/PoolC/SigAhri/blob/master/src/containers/Register/Register.tsx#L81))

**Comment by hcpak** [comment]
토큰이 만료되었을 때와 비밀번호가 틀렸을 때 모두 UnauthenticatedException을 통해 보내고 있었는데, 인터넷으로 검색한 결과 토큰이 만료되었을 때는 HTTP 상태코드를 401으로 보내야 하고(https://www.drupal.org/project/simple_oauth/issues/3041518#:~:text=According%20to%20the%20rfc6750%20spec,a%20401%2C%20not%20a%20403.&text=invalid_token%20The%20access%20token%20provided,401%20(Unauthorized)%20status%20code.),
비밀번호가 틀렸을 때 HTTP 상태코드를 403으로 보내야 한다고 합니다.(https://aloneonahill.com/blog/http-status-codes#:~:text=403%20%2D%20Forbidden,allow%20what%20was%20being%20asked.) 
따라서 각각 상황에 맡게 상태코드를 보내기 위해서 부득이 하게 Exception을 분리했습니다. 물론 저도 exception을 추가하는 게 맞나 고민을 했지만, 일단 이 때 이 문제를 해결할 수 있는 좋은 방법이 떠오르지 않았고 CommonExceptionHandler에서 전범위에서 동작하기 때문에 통일성을 위해 exception을 분리해야겠다는 생각이 들어 다음과 같이 코드를 짰습니다. 이 부분을 좀 더 생각해보겠습니다.

그리고 앞으로 비슷한 상황에서 상태코드가 같을 시에는 에러 코드나 메시지를 통해 구분하도록 하겠습니다.

**Comment by Jjungs7** [comment]
토큰만료됐을땐 401로 보내야하는건 동의합니다
근데 id, pw 틀렸을때 403 보내는건 [이 글](https://kimdoky.github.io/http/2018/12/30/401_403/)이나 [이 글](https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses) 참고해보는건 어떨까요?
이런 표준을 정하는 RFC가 애초에 비번 틀렸을땐 403, 토큰이 잘못됐을땐 401 이렇게 정해준건 아니라서 사람마다 해석이 다를 순 있는데요, 보통은 홈페이지에 접속할때 순서가 인증 -> 인가 받는 순서일거예요.
여기서 id, pw 틀렸을 때 저희는 먼저 회원 **인증**을 먼저 하려고 하니까 순서상 401이 더 맞지 않을까요? 물론 403도 틀린건 아니지만 401이 더 맞다고 생각해요
물론 제 말이 정답이 아니기 때문에 참고만 하셔도 됩니다. 이 이슈는 일단 close 하고 나중에 리팩토링이 필요할 경우 다시 이슈를 열어도 될 것 같네요
