### ISSUE TITLE
출석체크 회차 넘버링

### ISSUE THREAD

**Issue by dkstlzu** [PoolC/Mincho#134]
## 🗣 설명
세미나 출석체크 주차가 0주차 부터 시작되더라구요 1주차 부터 시작되도록 변경 바랍니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 세미나 출석체크 시작 넘버링 변경

**Comment by hcpak** [comment]
지금 0주차로 되어 있는 이유는 front 쪽에서 0부터 넣어주기 때문에 발생하는 문제라 제가 해결하긴 어렵습니다.
