### ISSUE TITLE
출석체크 첨부파일 관리

### ISSUE THREAD

**Issue by dkstlzu** [PoolC/Mincho#135]
## 🗣 설명
출석체크 시에 해당 회차에서 이용한 세미나 자료를 첨부하고 싶은데 출석체크 페이지에서는 첨부파일을 넣을 수 있는 버튼이 없습니다.
때문에 게시판에서 임의로 파일을 첨부한뒤 해당 링크를 연결하는 방식으로 사용했는데 출석체크 화면에서도 원하는 파일을 첨부할 수 있으면 좋겠습니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 출석체크화면 파일 첨부 기능 추가

**Comment by hcpak** [comment]
이번 주 내로 해결하도록 하겠습니다.

**Comment by hcpak** [comment]
저는 기능 구현 완료했는데 @mingd1023 님이 많이 바쁘신가봐요 ^^
