### ISSUE TITLE
UNACCEPTED 멤버 로그인 관련 오류

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#138]
## 🗣 설명

UNACCEPTED 멤버 로그인 관련 오류가 발생합니다.
1. 로그인은 되지만, 새로고침하면 바로 로그인이 풀립니다.
2. 로그인 후 member 정보가 오지 않습니다. (/member/me로 요청 시 403 응답)

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by hcpak** [comment]
원인은 파악했습니다. 근데 어떻게 고쳐야 부작용이 없는지 생각해보겠습니다.
