### ISSUE TITLE
새로운 기능 추가를 위한 DB 구조 설계

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#3]
## 🗣 설명

새로운 기능을 추가하기 위해 DB 구조 설계하기

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 세미나/스터디/출석체크/해시태그 관련 테이블
2. 동방 서적/대출 현황 관련 테이블

**Comment by hcpak** [comment]
member이랑 isExcepted char(1024)로 되어있는데 bool로 바꿔야 할거 같습니다. 제가 잘못적어서 죄송합니다.

**Comment by hcpak** [comment]
activity table의 host column에서 member의 연관 관계 주입을 해야할 거 같습니다. 제 생각엔 N:M이 되어야 할 거 같은데, 논의를 해봐야할 거 같습니다.
