### ISSUE TITLE
회원가입시 internal server error bug

### ISSUE THREAD

**Issue by yoonseokch** [PoolC/Mincho#80]
## 🗣 설명

회원가입시 제대로된 error message를 도출하지 않습니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 중복된 id를 가진 회원가입시 Conflict status code가 와야하는데 internal server error가 옵니다.
2. 잘못된 형식의 정보( ex 학번이 10자리가 아니라거나 email에 @가 없는 경우) Bad Request code가 와야하는데 internal server error가 옵니다.

**Comment by hcpak** [comment]
에러가 나는 이유는 Exception Handler가 작동하지 않기 때문이라는 것
