### ISSUE TITLE
프로젝트 조회 시 응답 형태 변경

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#81]
## 🗣 설명

현재 응답은

<img width="205" alt="스크린샷 2021-02-26 오후 11 54 51" src="https://user-images.githubusercontent.com/48787170/109315580-05a01b00-788e-11eb-9536-b7a5ba9b15f2.png">

이렇게 오는데, memberUUID를

members: [
{loginID 또는 memberUUID,
profileImageURL,
name,
department,
isAdmin
}, ...]

으로 수정해주셔야 할 것 같습니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by yoonseokch** [comment]
제가 확인해봤는데 api 명세대로 제가 작성해놨었는데 코드 리뷰에 따라서 members라고 하면 이해가 잘 안된다 라는 의견이 있어서  memberUUID로 수정되어 있는 상태입니다 내일 api명세 갱신하도록 하겠습니다..! 이래서 아스키독스를 쓰는거군요 ㅠㅠ

**Comment by mingd1023** [comment]
> 제가 확인해봤는데 api 명세대로 제가 작성해놨었는데 코드 리뷰에 따라서 members라고 하면 이해가 잘 안된다 라는 의견이 있어서 memberUUID로 수정되어 있는 상태입니다 내일 api명세 갱신하도록 하겠습니다..! 이래서 아스키독스를 쓰는거군요 ㅠㅠ

빠른 답변 감사합니다~ 그런데 멤버의 uuid뿐만 아니라 여러 정보를 담아오기 때문에 members로 하는 편이 낫지 않나요...?? 
또 멤버 이름으로 검색하는 api 잘 동작하는지 확인 부탁드립니다! 요청 보내봤는데 상태코드는 200이지만 데이터가 비어 있더라고요 존재하는 이름으로 검색했는데도요,,!

**Comment by yoonseokch** [comment]
원래 멤버데이터가 잘오는것을 확인을 한 후 인수테스트까지 완료하고 커밋을 해놓았었습니다. 근데 정일님이 여기있으면 안되는 api라고 하시고 현재 empty set을 return 하도록 해놓은 상태입니다. 내일 api 명세 바꾸고 수정해놓겠습니당

**Comment by yoonseokch** [comment]
members 로 수정하였습니다. 또한 member name으로 찾는 경로가 member/name으로 변경되었으니 참고 바랍니다

**Comment by mingd1023** [comment]
> members 로 수정하였습니다. 또한 member name으로 찾는 경로가 member/name으로 변경되었으니 참고 바랍니다

잘 작동합니다! 수고 많으셨습니다~
