### ISSUE TITLE
멤버 조회 시 응답 변경 & 회원가입 시 자기소개(introduciton)

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#82]
## 🗣 설명

<img width="233" alt="스크린샷 2021-02-27 오전 2 28 28" src="https://user-images.githubusercontent.com/48787170/109334000-7bfb4800-78a3-11eb-8df7-ad56fb2cdc20.png">

위 사진은 현재 응답입니다.
회원이 참여한 프로젝트와 활동들을 보여줘야 하므로,
project, activity 테이블도 join하도록 변경 부탁드립니다.

{
    name,
    department,
    profileImageURL,
    isAdmin,
    introduction,
    projects,
    activities,
  }

변경 후에는 이런 응답이 되어야 할 것 같습니다.

또한 회원가입을 할 때 introduction을 보내도 빈 문자열이 저장되는 것 같습니다.
request로 온 introduction이 저장될 수 있도록 수정 부탁드립니다

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by hcpak** [comment]
네 확인하고 수정하겠습니다!
