### ISSUE TITLE
관리자 임명/해임 시 발생하는 문제

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#83]
## 🗣 설명

<img width="713" alt="스크린샷 2021-02-27 오전 9 54 15" src="https://user-images.githubusercontent.com/48787170/109369930-c26f9780-78e1-11eb-830e-8ab3fbf65e16.png">

api 명세대로 요청을 보내도 자꾸 에러가 발생합니다.
요청 형태가 저게 맞는지 확인 부탁드립니다.
req body가 
{
isAdmin: true
}
이런 모양이 되는 게 맞나요? 아니면
true
이런 식으로 boolean 값만 보내야 하나요?
(근데 어차피 두 방식 모두 시도해봐도 오류가 나긴 합니다..)

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by hcpak** [comment]
그거 @Jjungs7 님이 수정하게 되면서 양식이 바뀌었습니다. isActivated을 boolean 받던 게 다음과 같이 바뀌었습니다. 그 api 명세도 수정하도록 하겠습니다.
![스크린샷 2021-02-27 오전 10 03 14](https://user-images.githubusercontent.com/68177113/109370288-09aa5800-78e3-11eb-87fb-bf7fe3ab585b.png)

**Comment by mingd1023** [comment]
> 그거 @Jjungs7 님이 수정하게 되면서 양식이 바뀌었습니다. isActivated을 boolean 받던 게 다음과 같이 바뀌었습니다. 그 api 명세도 수정하도록 하겠습니다.
> ![스크린샷 2021-02-27 오전 10 03 14](https://user-images.githubusercontent.com/68177113/109370288-09aa5800-78e3-11eb-87fb-bf7fe3ab585b.png)

이런 일을 방지하기 위해서 asciidoc 쓰는 게 좋을 것 같습니다...! 제가 작성한 제일 최근 이슈 읽어주시면 감사드리겠습니다~
