### ISSUE TITLE
Book update 시 오류 발생

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#85]
## 🗣 설명

<img width="1457" alt="스크린샷 2021-02-27 오후 5 36 40" src="https://user-images.githubusercontent.com/48787170/109382198-5b260780-7922-11eb-98e6-6702747bac1b.png">
<img width="328" alt="스크린샷 2021-02-27 오후 5 37 05" src="https://user-images.githubusercontent.com/48787170/109382208-6c6f1400-7922-11eb-90a6-0aa1d965442f.png">
<img width="518" alt="스크린샷 2021-02-27 오후 5 37 26" src="https://user-images.githubusercontent.com/48787170/109382215-77c23f80-7922-11eb-8746-99a8c13f5b33.png">

클라이언트에서 요청은 제대로 보낸 것 같은데, book update 시 409 conflict 에러가 발생합니다.
확인 부탁드립니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by yoonseokch** [comment]
같은 책이 여러개 동시에 들어갈수 없게 설정되어 있는데 혹시 책 제목과 저자가 같은 다른 책이 존재하나요?

**Comment by mingd1023** [comment]
> 같은 책이 여러개 동시에 들어갈수 없게 설정되어 있는데 혹시 책 제목과 저자가 같은 다른 책이 존재하나요?

아니요! 책은 딱 한 권만 넣어놓았고 그 한 권을 수정하려 할 때 문제가 발생했습니다

**Comment by yoonseokch** [comment]
수정하였습니다!

**Comment by mingd1023** [comment]
> 수정하였습니다!

에러는 발생하지 않으나 데이터가 업데이트되지 않는 것 같습니다ㅜㅜ

**Comment by yoonseokch** [comment]
다시 확인 부탁드립니다 ㅠㅠ 죄송합니다

**Comment by mingd1023** [comment]
> 다시 확인 부탁드립니다 ㅠㅠ 죄송합니다

이제 잘 됩니다~ 수고 많으셨어요
