### ISSUE TITLE
프로젝트 수정 시 오류 발생

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#86]
## 🗣 설명

백엔드에서 클라이언트 request 중 프로젝트 body (프로젝트 설명)을 무시하는 것 같습니다.
확인 부탁드립니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by yoonseokch** [comment]
수정완료하였습니다 확인 부탁드립니당

**Comment by mingd1023** [comment]
> 수정완료하였습니다 확인 부탁드립니당

잘 작동합니다! 감사합니다~
