### ISSUE TITLE
도서 목록 조회 시 borrowDate 불러오지 않음

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#87]
## 🗣 설명

도서 목록 조회 시 현재 borrowDate를 가지고 오지 않습니다.
borrowDate도 포함해서 정보를 보내주세요!

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by yoonseokch** [comment]
이거도 삭제가 되었네요 다시 한번 살펴보겠습니다

**Comment by yoonseokch** [comment]
확인해주세용

**Comment by mingd1023** [comment]
네 잘 되네요! 빠른 수정 감사합니다👍🏻
