### ISSUE TITLE
board의 permission enum을 모두 가져오는 api

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#89]
## 🗣 설명

board의 permission enum은 어떤 종류가 있는지 가져오는 api가 필요합니다.
구현해서 명세 작성해주시면 감사드리겠습니다~

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by Jjungs7** [comment]
f8c513fcde01f0f79791f4148907f5db2f769567
GET /member/role 권한으로 통합해도 될 것 같아요
