### ISSUE TITLE
학기별 activity 조회 문제

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#92]
## 🗣 설명

<img width="410" alt="스크린샷 2021-03-03 오후 8 31 24" src="https://user-images.githubusercontent.com/48787170/109799456-6d27e300-7c5f-11eb-91e9-319e53b6328e.png">

전체 조회 api를 이용하면 위와 같이 잘 응답이 오는데,

<img width="647" alt="스크린샷 2021-03-03 오후 8 32 03" src="https://user-images.githubusercontent.com/48787170/109799567-8597fd80-7c5f-11eb-9e79-64a3c47b74e7.png">

when에 조건을 넣어 위와 같이 요청을 보내면 응답이 오지 않습니다.
이 부분 확인 부탁드립니다.
1학기의 활동들은 잘 불러오는데, 2학기 활동들을 불러올 때 문제가 있는 것 같습니다.

또한 학기들을 불러올 때, 최신 순으로 order를 정하여 가지고 오면 좋을 것 같습니다.
2021-1
2020-2
2020-1
...

이런 식으로요!

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by yoonseokch** [comment]
죄송합니다 확인부탁드립니다
