### ISSUE TITLE
activity api 개선

### ISSUE THREAD

**Issue by Jjungs7** [PoolC/Mincho#95]
## 🗣 설명
[/session/{activityID}](https://github.com/PoolC/Mincho/blob/3795b37df2c11f0eca8c3d190b5c7413fe95e981/src/main/java/org/poolc/api/activity/controller/ActivityController.java#L58) 와 /onesession/{sessionID} 보단
/session/activity/{activityID} 와
/session/{sessionID} 는 어떠실지

**Comment by yoonseokch** [comment]
민지님 저렇게 바꿔도 될까요?

**Comment by mingd1023** [comment]
> 민지님 저렇게 바꿔도 될까요?

네 괜찮아요~~

**Comment by yoonseokch** [comment]
api 수정하고 docs에 반영하였습니당
